#!/bin/bash

files=$(git diff --cached --name-only)
for file in $files; do
  if [[ $file == *.py ]]; then
    echo -e "\x1b[38;2;119;221;119m[Info]\x1b[0m Running black formatter on $file"
    black "$file"
    echo -e "\x1b[38;2;119;221;119m[Info]\x1b[0m Running isort formatter on $file"
    isort "$file"
    git add "$file"
  fi
done

commit_msg=$(cat $1)
